# Generated by Django 3.1.6 on 2021-02-10 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210210_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aktor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=32)),
                ('nazwisko', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czas_trwania', models.IntegerField()),
                ('rodzaj', models.IntegerField(choices=[(0, 'Nieznany'), (2, 'Sci-fi'), (3, 'Drama'), (4, 'Komedia'), (1, 'Horror')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=32)),
                ('opis', models.TextField(max_length=256)),
                ('po_premierze', models.BooleanField(default=False)),
                ('premiera', models.DateField(blank=True, null=True)),
                ('rok', models.IntegerField()),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('extra_info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.extrainfo')),
            ],
        ),
        migrations.CreateModel(
            name='Recenzja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField(default='')),
                ('gwiazdki', models.IntegerField(default=5)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recenzje', to='api.film')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='aktor',
            name='filmy',
            field=models.ManyToManyField(to='api.Film'),
        ),
    ]
