# Generated by Django 3.1.6 on 2021-02-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='on_stock',
            field=models.IntegerField(default=999, max_length=3),
        ),
    ]
