# Generated by Django 3.1.6 on 2021-02-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_product_on_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='on_stock',
            field=models.IntegerField(default=999),
        ),
    ]
